name: Test AzureOCR

on:
  push:
    branches:
      - main
      - ci
      - release/*
      - feature/*
    tags:
      - v*
    paths-ignore:
      - README*
  pull_request:

jobs:
  test_linux:
    name: Test ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.10"
            tesseract5: true
          - os: ubuntu-latest
            python: "3.11"
            tesseract5: true
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0" # 0=all, needed for setuptools-scm to resolve version tags

      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Install Tesseract 5
        if: matrix.tesseract5
        run: |
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel

      - name: Install common packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            curl \
            ghostscript \
            img2pdf \
            libexempi8 \
            libffi-dev \
            libsm6 libxext6 libxrender-dev \
            pngquant \
            poppler-utils \
            tesseract-ocr \
            tesseract-ocr-deu \
            tesseract-ocr-eng \
            tesseract-ocr-osd \
            unpaper \
            zlib1g

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --prefer-binary .[test]

      - name: Report versions
        run: |
          tesseract --version
          gs --version
          pngquant --version
          unpaper --version
          img2pdf --version

      - name: Run Test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: |
          python -m pytest tests/
        
